<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
<style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table, th, td {
            border: 1px solid #ddd;
        }

        th, td {
            padding: 10px;
            text-align: left;
        }
        h2{
            margin:90px;
        }
   
    </style>


<h2>Liste des Clients</h2>

<div class="container">
<table class="table-light">
    <thead>
        <tr class="table-light">
            <th>Nom</th>
            <th>Prenom</th>
            <th>Email</th>
            <th>Tel</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($clients as $client): ?>
            <tr class="table-light">
                <td><?= $client['nom'] ?></td>
                <td><?= $client['prenom'] ?></td>
                <td><?= $client['email'] ?></td>
                <td><?= $client['Tel'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>