
    <div id="app">
            <div class="video">
                <video autoplay  loop muted  plays-inline>
                          <source  src="../assets/vidéos/louis.mp4"  type="video/mp4">
                </video>
            </div>
            <div class="cont">
                <h3>The Holiday Season with Louis Vuitton</h3>
                <a href="#"id="button">Discover The Gift Guide</a>
            </div>


      


            <img src="../assets/images/PUSH3_COLORMANIA_US_DI3.jpg" alt="" class="products_img">
           <div class="cont">
            <h3> Louis Vuitton Colormania</h3>
            <a href="#"id="button">Discover The Collection</a>
           </div>
          <div class="video">
        <video   autoplay  loop muted  plays-inline >
               <source src="../assets/vidéos/sac.mp4" >
       </video>
        </div>
       <div class="cont">
        <h3> Cruise 2024</h3>
        <a href="#"id="button">Discover The Collection</a>
    </div>
    <img src="../assets/images/PUSH7_HOLIDAY_FRAGRANCES_US_DI3.webp" alt="" class="products_img">
    <div class="cont">
        <h3> Signature Scents</h3>
        <a href="#"id="button">Discover The Collection</a>
    </div>
    </div>
</div>
<footer >
   <div class="services">
         <h1>Services</h1>
         <div class="bodyservices">
            <div>
            <img src="../assets/images/Contact_Us.webp" class="services_img">
            <p><strong>How Can We Help You?</strong>
                <br>Wherever you are,Luis Vuitton Client Advisors will be delighted to assist you .<br><a href="#">Contact Us</a></p>
            </div>
            <div>
            <img src="../assets/images/Art_Of_Gifting.webp" class="services_img">
            <p><strong>Art of Gifting</strong>
                <br>Choose the perfect gift from our specially curated selection of products. <br><a href="#">Gift for Her</a></p>
                </div>
                <div>
            <img src="../assets/images/Personalization.webp" class="services_img">
            <p><strong>Personalization</strong>
                <br> Luis Vuitton's Personalization offer spans a wide range of services.<br><a href="#">Explore  our Collections</a></p>
            </div>
         </div>
    </div>

</footer>

