<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../assets/index.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css"> 
    <link rel="icon"type="image/jpg" href="../assets/images/logo2.jpg">
    <title><?= $titrepage ?></title>
</head>

<body>
    <div id="app">


            <div class="Menucontent">
                <a href="index.php">Gifts</a><br><br>
                <a href="women.php">Women</a><br><br>
                <a href="#">Men</a><br><br><hr>
                <p>Sustainability</p>
                <p>MyLV</p>
                <p>Find a Store </p>
                <p>Ship to:United States</p>
                <p>Wishlist</p>
                <p>Can we help you?</p>
                <p>+1.866.VUITTON</p>
            </div>
       
        <div class="nav-bar" >
                <ul class="menu">
                  <li id="Menu"><a href="#" class="lien"><i class="bi bi-list"></i> Menu</a></li>
                  <li ><a href="#"class="lien"><i class="bi bi-search"></i> Search</a></li>
                  <h1 id="LV">LOUIS  VITTON</h1>
                    <li>Call Us</li>
                    <li>Wishlist</li>
                    <a href="./login.php"><li> My LV</li></a>
                    <li><a href="#"class="lien"><i class="bi bi-basket3"><span>1</span></i></a></li>
                </ul>
        </div>
    <div>
        <?php include $template.'.phtml';
        ?>
</div>
<footer >
    <div class="informations">
        <ul>
            <li> Ship to:United States</li>
            <li> Sitemap</li>
            <li>Legal Notices</li>
            <li>Privacy Policy</li>
            <li>California Supply Chains Act</li>
            <li>Do Not Sell or Share My Personal Informations </li>
            <li>Accessibility</li>
        </ul>
        <a href="index.php">goShop</a>
        <h2>LOUIS VUITTON</h2>

    </div>
</footer>

<script src="../js/NavBar.js"></script>

</body>
</html>