<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-dZlMzVo3U8i+6e+jJ0WqzTE2imEnj7PMP1z5X5+C/70I+P/qcEkFZE/XJ/DA1Dj" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../assets/login.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <div class="container" style=" whidth: 25rem;">
        <form action="login.php" method="post">
            <h2>Login</h2>
            <?php 
            if(array_key_exists("error",$_GET)):
             ?>
            <div class="alert alert-danger">
                 <?= $_GET['error']; ?>
            </div>
             <?php endif ?>
            <label for="username">Email adress:</label>
            <input type="email" id="username" name="email" required>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required><br>
            <button type="submit" class="btn-btn">Login</button>
        </form>
        <hr>
        <p class="text-center mt-3">I don't have an account</p>
        <p class="text-center mt-3"> Enjoy added benefits and a richer experience by creating a personal account </p>
        <a href="inscri.php" class="btn">Create My LV Account </a>
    </div>

   


