<form action="process_change_password.php" method="post">
    <h2>Changer le mot de passe</h2>

    <label for="oldPassword">Ancien mot de passe:</label>
    <input type="password" id="oldPassword" name="oldPassword" required>
<br>
    <label for="newPassword">Nouveau mot de passe:</label>
    <input type="password" id="newPassword" name="newPassword" required>
<br>
    <label for="confirmPassword">Confirmer le nouveau mot de passe:</label>
    <input type="password" id="confirmPassword" name="confirmPassword" required>
<br>
    <button type="submit" style="color:white; background-color:black; padding-left:20px ; padding-right:20px">
    Changer le mot de passe</button>
</form>