 <link rel="stylesheet" href="../assets/WomenStyles.css">
    <div >
            <video autoplay  loop muted  plays-inline class="video_women">
                <source  src="../assets/vidéos/LV Volt Collection _ LOUIS VUITTON.mp4"  type="video/mp4">
            </video>
             <h2 class="titre">women</h2>
        <div class="Dresses">
            <h5 class="dresstype">Dresses</h5>
            <div class="Dressescards">
               <div class="card" >
                <img src="../assets/images/louis-vuitton-eyelet-tab-dress --FQJD12GXW900_PM2_Front view.webp" type="image/avif" alt="">
                <div class="card-body">
                    <p class="card-title">Eyelet Tab Dress</p>
                    <p class="price">$2,200.00</p>
                    <a href="#" class="btn">Ajouter au panier</a>
                </div>
               </div> 
                 <div class="card">
                <a href="Details.html"><img src="../assets/images/louis-vuitton-3d-bustier-velvet-hem-dress--FPRO43CQF900_PM2_Front view.webp" type="image/avif" alt="Nom de l'article"></a>
                <div class="card-body">
                    <p class="card-title">Bustier Velvet Hem Dress</p>
                    <p class="price">$5,650.00</p>
                    <a href="#" class="btn">Ajouter au panier</a>
                </div>
                </div> 
                 <div class="card">
                <img src="../assets/images/louis-vuitton-graphic-pleated-accent-gown --FQDR02NJ8002_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                <div class="card-body">
                    <p class="card-title">Graphic Pleated Accent Gown</p>
                    <p class="price">$5,300.00</p>
                    <a href="#" class="btn">Ajouter au panier</a>
                </div>
                </div> 
                 <div class="card">
                <img src="../assets/images/louis-vuitton-tweed-pocket-dress --FQDS89GFE900_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                <div class="card-body">
                    <p class="card-title">Tweed Pocket Dress</p>
                    <p class="price">$3,300.00</p>
                    <a href="#" class="btn">Ajouter au panier</a>
                </div>
                 </div> 
                 <div class="card">
                    <img src="../assets/images/louis-vuitton-zipper-neckline-dress --FQDR37SM4900_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                    <div class="card-body">
                        <p class="card-title">Zipper Neckline Dress</p>
                        <p class="price">$3,550.00</p>
                        <a href="#" class="btn">Ajouter au panier</a>
                    </div>
                     </div> 
                     <div class="card">
                        <img src="../assets/images/louis-vuitton-ruffle-detail-dress--FQDR40QCY900_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                        <div class="card-body">
                            <p class="card-title">Ruffle Detail Dress</p>
                            <p class="price">$4,050.00</p>
                            <a href="#" class="btn">Ajouter au panier</a>
                        </div>
                         </div> 
            </div>

        </div>

        <div class="Handbags">
            <h5>Handbags</h5>
            <div class="Handbagscards">
                <div class="card">
                 <img src="../assets/images/louis-vuitton-lock-go--M22311_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                 <div class="card-body">
                     <p class="card-title">Lock & Go</p>
                     <p class="price">$3,200.00</p>
                     <a href="#" class="btn">Ajouter au panier</a>
                 </div>
                </div> 
                  <div class="card">
                 <img src="../assets/images/louis-vuitton-multi-pochette-accessoires--M80399_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                 <div class="card-body">
                     <p class="card-title">Multi Pochette Accessoires</p>
                     <p class="price">$2,840.00</p>
                     <a href="#" class="btn">Ajouter au panier</a>
                 </div>
                 </div> 
                  <div class="card">
                 <img src="../assets/images/louis-vuitton-onthego-east-west--M23640_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                 <div class="card-body">
                     <p class="card-title">OnThe Go East West</p>
                     <p class="price">$3,150.00</p>
                     <a href="#" class="btn">Ajouter au panier</a>
                 </div>
                 </div> 
                  <div class="card">
                 <img src="../assets/images/louis-vuitton-nano-speedy--M82450_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                 <div class="card-body">
                     <p class="card-title">Nano Speedy</p>
                     <p class="price">$1,900.00</p>
                     <a href="#" class="btn">Ajouter au panier</a>
                 </div>
                  </div> 
                  <div class="card">
                     <img src="../assets/images/louis-vuitton-onthego-pm--M46569_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                     <div class="card-body">
                         <p class="card-title">OnThe Go PM</p>
                         <p class="price">$3,250.00</p>
                         <a href="#" class="btn">Ajouter au panier</a>
                     </div>
                      </div> 
                      <div class="card">
                         <img src="../assets/images/louis-vuitton-pochette-métis-east-west--M22942_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                         <div class="card-body">
                             <p class="card-title">Pochette Metis East Wesr</p>
                             <p class="price">$2,980.00</p>
                             <a href="#" class="btn">Ajouter au panier</a>
                         </div>
                          </div> 
             </div>
        </div>

        <div class="Necklaces">
            <h5>Necklaces and Pendants</h5>
            <div class="Necklacescards">
                <div class="card">
                 <img src="../assets/images/louis-vuitton-lv-x-yk-lv-iconic-infinity-dots-necklace--M01079_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                 <div class="card-body">
                     <p class="card-title">LV x YK LV Iconic Infinity Dots Necklace</p>
                     <p class="price">$660.00</p>
                     <a href="#" class="btn">Ajouter au panier</a>
                 </div>
                </div> 
                  <div class="card">
                 <img src="../assets/images/louis-vuitton-blooming-strass-necklace--M68374_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                 <div class="card-body">
                     <p class="card-title">Blooming Strass Necklace</p>
                     <p class="price">$650.00</p>
                     <a href="#" class="btn">Ajouter au panier</a>
                 </div>
                 </div> 
                  <div class="card">
                 <img src="../assets/images/louis-vuitton-lv-floragram-necklace--M00981_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                 <div class="card-body">
                     <p class="card-title">LV Floragram Necklace</p>
                     <p class="price">$585.00</p>
                     <a href="#" class="btn">Ajouter au panier</a>
                 </div>
                 </div> 
                  <div class="card">
                 <img src="../assets/images/louis-vuitton-lv-heirloom-necklace--M01282_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                 <div class="card-body">
                     <p class="card-title">LV Floragram Necklace</p>
                     <p class="price">$585.00</p>
                     <a href="#" class="btn">Ajouter au panier</a>
                 </div>
                  </div> 
                  <div class="card">
                     <img src="../assets/images/louis-vuitton-lv-x-yk-lv-iconic-infinity-dots-necklace--M01081_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                     <div class="card-body">
                         <p class="card-title">LV Heirloom Necklace</p>
                         <p class="price">$2,050.00</p>
                         <a href="#" class="btn">Ajouter au panier</a>
                     </div>
                      </div> 
                      <div class="card">
                         <img src="../assets/images/louis-vuitton-blooming-strass-necklace--M68374_PM2_Front view.webp" type="image/avif" alt="Nom de l'article">
                         <div class="card-body">
                             <p class="card-title">LV x YK LV Iconic Infinity Dots Necklace</p>
                             <p class="price">$660.00</p>
                             <a href="#" class="btn">Ajouter au panier</a>
                         </div>
                          </div> 
             </div>

        </div>
    </div>
    <footer >
   <div class="services">
         <h1>Services</h1>
         <div class="bodyservices">
            <div>
            <img src="../assets/images/Contact_Us.webp" class="services_img">
            <p><strong>How Can We Help You?</strong>
                <br>Wherever you are,Luis Vuitton Client Advisors will be delighted to assist you .<br><a href="#">Contact Us</a></p>
            </div>
            <div>
            <img src="../assets/images/Art_Of_Gifting.webp" class="services_img">
            <p><strong>Art of Gifting</strong>
                <br>Choose the perfect gift from our specially curated selection of products. <br><a href="#">Gift for Her</a></p>
                </div>
                <div>
            <img src="../assets/images/Personalization.webp" class="services_img">
            <p><strong>Personalization</strong>
                <br> Luis Vuitton's Personalization offer spans a wide range of services.<br><a href="#">Explore  our Collections</a></p>
            </div>
         </div>
    </div>
</footer>


